language: ruby
sudo: false 

before_install: 
 - gem install codecov
 - pip insyall coveragepy
install:
 - gem install jekyll
 - gem install jekyll-seo-tag
script:
 - coverage jekyll build

after_success:
  - bash <(curl -s https://codecov.io/bash)