language: ruby
sudo: false 
export CODACY_PROJECT_TOKEN=2cc7a73638c14d7382d9cf0ac41e9b77
before_install: 
 - gem install codecov
 - gem install coveralls
install:
 - gem install jekyll
 - gem install jekyll-seo-tag
script:
 - jekyll build

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) 
  - bash < (curl -s https://codecov.io/bash)
