language: ruby
sudo: false 

before_install: 
 - gem install codecov
install:
 - gem install jekyll
 - gem install jekyll-seo-tag
script:
 - jekyll build

after_success:
  - bash <（curl -Ls https://coverage.codacy.com/get.sh ）
  - bash < (curl -s https://codecov.io/bash)
