version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    executor: ruby/default
    steps:
      - checkout
      - run:
        - gem install jekyll-seo-tag
        - jekyll build
